---
apiVersion: v1
kind: Secret
metadata:
  name: my-quarkus-service-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/janus-idp-demo/my-quarkus-service-gitops